# Generated by Django 6.0.1 on 2026-01-29 09:59

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=10, unique=True)),
                ('empname', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('faculty', 'Faculty'), ('hod', 'HOD'), ('admin', 'Admin'), ('security', 'Security')], max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[app1.models.validate_svrec_email])),
            ],
            options={
                'db_table': 'login',
            },
        ),
    ]
