# Generated by Django 6.0.1 on 2026-01-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='role',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('hod', 'HOD'), ('admin', 'Admin'), ('security', 'Security'), ('principal', 'Principal'), ('office', 'Office'), ('clerk', 'clerk')], max_length=20),
        ),
    ]
