# Generated by Django 6.0.1 on 2026-01-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_login_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='role',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('hod', 'HOD'), ('admin', 'Admin'), ('security', 'Security'), ('principal', 'Principal'), ('office', 'Office'), ('clerk', 'Clerk')], max_length=20),
        ),
    ]
