# Generated by Django 5.2.8 on 2026-02-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_login_otp_alter_login_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
